### ISSUE TITLE
Compare LodeRunner, MegaMan, Zelda, and Mario Level generation for CMA-ME 

### ISSUE THREAD

**Issue by MBatt1** [schrum2/MM-NEAT#645] opened 2021-05-19 21:10 UTC
Should resolve the issues with CMA-ME emitters beforehand.

**Comment by schrum2** [comment] 2021-05-20 03:17
Include Zelda too

**Comment by schrum2** [comment] 2021-05-21 19:23
In `batch\Experiments-2021-MoreCPPN2GAN` there are batch files with `Direct` at the end. Add a new `Experiments-2021-CMAME` directory and copy those batch files here. However, rename the `Direct` part to be `ME`. You will also need to change the save and logging locations, and the base dir. The point is to compare these previous experiments, which evolve vectors with regular MAP-Elites, to new batch files that are similar, but replace MAP-Elites with CMAME. However, we need to account for different types of emitters. Have options for 1Improvement, 2Improvement, and ImprovementOptimizing (one of each)

Let's do this first and worry about other games later.

**Comment by MBatt1** [comment] 2021-05-21 20:09
Added Mario and Zelda batch files, currently running two mario ones

**Comment by schrum2** [comment] 2021-05-21 20:11
When you get around to batch files for LodeRunner, use the ones trained on 150 levels as a starting point for comparison. When using plain MAP Elites, it was hard to find solutions using that particular GAN, so it would be interesting to see if CMAME does much better. Probably don't want to make a ton of batch files for this though ... just compare the On150Levels GAN first and we'll see where to go from there.

**Comment by MBatt1** [comment] 2021-05-24 14:56
![image](https://user-images.githubusercontent.com/53229958/119366122-3f5aa500-bc76-11eb-9a1e-7ac762be42a8.png)
Results from Mario Decorate NS Leniency

**Comment by schrum2** [comment] 2021-05-24 15:11
The point of these results is to show that CMA-ME doesn't seem to be doing as well as it should. So, we either still have a problem with our implementation, or the difference in binning scheme makes a meaningful difference. In the worst case, we may have to open up the CMA-ME issue again, but let's do more experiments with Zelda first.

**Comment by schrum2** [comment] 2021-06-01 15:30
I can further confirm that CMA-ME either has problems or doesn't work in Zelda. Here is a simple comparison of plain MAP-Elites vs CMA-ME with one Improvement Emitter:
![image](https://user-images.githubusercontent.com/8397236/120350051-401db780-c2c4-11eb-91b1-56c17944a8c5.png)
CMA-ME QD scores are on a much smaller scale.

I have similar results from the other CMA-ME binning scheme in Zelda too.

**Comment by schrum2** [comment] 2021-06-03 19:39
I also ran some Zelda experiments with CMA-ME and MAP-Elites
![image](https://user-images.githubusercontent.com/8397236/120702065-43a66f80-c479-11eb-8207-518f77f31c63.png)
My plain MAP-Elites results match yours, which makes sense. However, although my CMA-ME results are still worse than MAP-Elites, they are better than yours. I think this is because I used 5 improvement emitters whereas you used just 1. Also, the 5 emitter performance was pretty close to plain MAP-Elites. This really makes me wonder where the ceiling on this is ... I guess we need to try 10 or even 15 improvement emitters for CMA-ME.

**Comment by schrum2** [comment] 2021-06-04 14:14
Running in Zelda with 10 emitters definitely caused an improvement. CMA-ME is now slightly better than pure MAP-Elites.
![image](https://user-images.githubusercontent.com/8397236/120815083-21622f80-c515-11eb-814f-e2a518d804d4.png)
The next step is to try with 15 emitters and see what happens. It would probably also be a good idea to both run longer, and to do repeated runs to verify the robustness of these results.

**Comment by schrum2** [comment] 2021-06-07 19:25
Running Zelda with 15 emitters did not produce better results, and we are once again suspicious of the correctness of our CMA-ME implementation. Amy indicated that just one emitter should be better than pure MAP-Elites, so we are definitely doing something wrong. An any case, here are the latest bad Zelda results with 15 emitters, compared to pure MAP-Elites.

![image](https://user-images.githubusercontent.com/8397236/121076626-3bfa0a00-c79c-11eb-8108-32bfa8d4d817.png)

**Comment by schrum2** [comment] 2021-06-18 18:31
Although we still suspect that our CMA-ME implementation has problems, it could be informative to do some new runs given all the changes that have happened to the code, perhaps in Lode Runner or Mario. We want to see if ANY examples exist where CMA-ME (our version) is better than MAP-Elites. Perhaps using the latent slicing bin scheme could help.

**Comment by schrum2** [comment] 2021-06-22 14:06
If CMA-ME really works now #664 , then this issue will become relevant again. In fact, you will need to do several comparisons, as with #669 and #693 . Wait until #664 is closed though.

**Comment by MBatt1** [comment] 2021-06-24 19:14
![MarioLevelsDecorateNSLeniency-CMAME5Improvement1_MAPElites_archive](https://user-images.githubusercontent.com/53229958/123319760-74b51580-d4f6-11eb-890c-eac3032a1589.gif)
Mario animated archive

**Comment by schrum2** [comment] 2021-06-25 12:28
@MBatt1 Please provide more commentary on the results you post so it is clear what we should be concluding. From what you posted before, it looks like CMA-ME for this particular Mario binning scheme is not really better than MAP-Elites. Therefore, try other binning schemes in other domains. In particular, it seems like the generalized latent vector approach could be promising. Should also include commentary regarding the fact that the previous experiment used a different sigma value. This could also have an impact.

**Comment by MBatt1** [comment] 2021-06-25 14:06
Another run was done with Mario to see if changing the starting sigma would have a positive effect,
![image](https://user-images.githubusercontent.com/53229958/123436699-81884680-d594-11eb-86c2-36f7cb0552c3.png)
the left column has a sigma of 0.2, while the right column has a sigma of 0.5.
0.5 is inferior to 0.2 in both max fitness and QD, but fills roughly the same amount of bins

**Comment by MBatt1** [comment] 2021-06-25 14:15
![image](https://user-images.githubusercontent.com/53229958/123437716-974a3b80-d595-11eb-9916-8b7073a096b3.png)
Here are some results from running Zelda with 5 emitters, and the default 0.5 sigma. 

Unfortunately, like Mario, these runs also appear to be worse than those from this paper: https://arxiv.org/pdf/2105.12960.pdf

**Comment by schrum2** [comment] 2021-06-29 14:54
Try doing a CMA-ME comparison in either Mega Man or Lode Runner, but this time, have a run with 1 emitter and another run with 5 emitters. I think a 1 emitter run will make it easier to observe what is happening when we watch the archive animation.

This clearly won't be part of the presentation at this point. It might be something to run over the weekend and investigate a bit during that last week.

**Comment by MBatt1** [comment] 2021-06-30 19:06
After CMA-ME changes, the Decorate, NS, Leniency binning scheme is not any better, being pretty much the same as before 
![image](https://user-images.githubusercontent.com/53229958/124017346-3911c400-d9ac-11eb-9dd6-404cbcf7d9b0.png)

**Comment by MBatt1** [comment] 2021-06-30 19:10
![image](https://user-images.githubusercontent.com/53229958/124017887-dbca4280-d9ac-11eb-8827-f1ac0b3a08de.png)
Decorate Leniency did show a slight improvement

**Comment by MBatt1** [comment] 2021-06-30 19:13
![MarioLevelsDecorateLeniency-CMAME5Improvement240_MAPElites_archive](https://user-images.githubusercontent.com/53229958/124018305-54310380-d9ad-11eb-9e20-1bff06e1dca6.gif)
![MarioLevelsDecorateLeniency-ME201_MAPElites_archive](https://user-images.githubusercontent.com/53229958/124018309-55623080-d9ad-11eb-8060-5fd19517a396.gif)

**Comment by MBatt1** [comment] 2021-06-30 19:14
![MarioLevelsDecorateLeniency-CMAME5Improvement240_MAPElites195](https://user-images.githubusercontent.com/53229958/124018388-69a62d80-d9ad-11eb-893a-c3696734bf35.png)
![MarioLevelsDecorateLeniency-ME201_MAPElites200](https://user-images.githubusercontent.com/53229958/124018376-657a1000-d9ad-11eb-9f85-0b0d064d45c7.png)

**Comment by schrum2** [comment] 2021-07-02 01:52
Not going to bother posting similar results again, but I just confirmed that despite the resampling fix ( #724 ) a run of `mariolevelsdecoratensleniency\CMAME1Improvement0` is still no better than it was before (which, as seen earlier in this same thread, is slightly worse than plain MAP Elites).

**Comment by schrum2** [comment] 2021-07-02 13:48
Looks like Zelda WWR results with CMA-ME are also comparable/inferior to plain MAP Elites. Here are the CMA-ME results:
![image](https://user-images.githubusercontent.com/8397236/124283813-f0741b00-db11-11eb-98a2-a8c88edeff98.png)
I'm comparing with the results from the ToG submission on arxiv (https://arxiv.org/pdf/2105.12960.pdf), specifically this figure:
![image](https://user-images.githubusercontent.com/8397236/124283953-1a2d4200-db12-11eb-8d1d-d3bdf7d1adc5.png)
Note that I'm only comparing against the red line, and both of these plots top out around 300 ... in fact, the plain MAP Elites results (with Direct2GAN) seem better than CMA-ME.

**Comment by schrum2** [comment] 2021-07-02 13:49
![ZeldaDungeonsWallWaterRooms-CMAME5Improvement0_MAPElites](https://user-images.githubusercontent.com/8397236/124284227-65dfeb80-db12-11eb-94f2-de5a6daede7c.png)
Also, here is the final Zelda WWR archive using CMA-ME with 5 improvement emitters.

**Comment by schrum2** [comment] 2021-07-06 21:33
The resampling mechanism seems to just lead to an almost infinite loop. The code just keeps generating samples over and over but gets stuck.

I'm fairly certain that CMA-ME is correctly implemented, but that it simply can't handle these particular binning schemes. CMA-ME worked for function optimization, at least for the Sphere function, and it was better than plan ME on Rastrigen. I would expect it to be at least better than plain MAP Elites in these game domains, but the binning scheme must have problems.

I'm going to close this issue. I would only revisit it if #721 reveals that the original pyribs does really well in our domains. Only that would convince me that we need to try more to fix our CMA-ME implementation.

**Closed by schrum2** 2021-07-06 21:33 UTC
Labels: Lode Runner, Mario, MegaMan, Zelda
