### ISSUE TITLE
DungeonNoveltyTest Sometimes Fails

### ISSUE THREAD

**Issue by cappsb** [schrum2/MM-NEAT#573] opened 2020-07-16 18:15 UTC
I believe this is related to #463. I suspect there may be something wrong with how the code handles not knowing how to place a node.

**Comment by schrum2** [comment] 2022-05-05 05:16
I haven't even noticed this test failing. Perhaps the issue is fixed, or the test was just disabled. In any case, this issue does not have much detail and is not really reproducible, so I'm closing the issue.

**Closed by schrum2** 2022-05-05 05:16 UTC
Labels: Zelda
