### ISSUE TITLE
dug holes don't always allow you to go though

### ISSUE THREAD

**Issue by kdsteckel** [schrum2/MM-NEAT#494] opened 2020-05-26 20:45 UTC
I also noticed that when you dig up the ground, you sometimes can't fall through the empty spot unless an adjacent location is also dug up. https://files.slack.com/files-pri/T8FKEK536-F014P2A4ZTK/image.png

**Comment by kdsteckel** [comment] 2020-05-26 20:49
First look in Dug class.

**Comment by kdsteckel** [comment] 2020-05-26 20:56
This also happens sometimes in the levels that are built into IceCreamYou code base 
@schrum2

**Comment by schrum2** [comment] 2020-05-26 21:58
Yes, but I think this is caused by the changes to made to the display size and the re-scaling. So, the error is not something that was already present ... rather, because you changed the code, this error affects both their levels and the VGLC levels. You have to figure out why. @kdsteckel

**Comment by schrum2** [comment] 2020-06-04 05:41
This issue is sort of a sub-issue of #472 . We'll keep both around, but you will eventually be able to close both at the same time.

**Comment by schrum2** [comment] 2020-06-05 16:54
I found this comment at the top of the `LodeRunner` class:
```
/**
 * KNOWN BUGS
 * - Due to a collision model where players are considered "on" a surface if they are touching it,
 *   players might sometimes be unable to fall into a hole that is just one unit wide.
 * - The player can dig even when there is something else on top of the hole.
 * - Enemies should not be able to occupy the same hole (enemies in holes should act like solids).
 * - On death, subtract gold points gained on that level so far.
 */
```
Was this in the original code @kdsteckel ? I guess we didn't cause this bug. This may make fixing it harder, but it is still worth a try.

**Comment by schrum2** [comment] 2020-06-05 17:42
@kdsteckel Please find a way to reliably witness the dug hole error occurring. We need a way to see the error so we will know if when we fix it. If you tell me how to produce it reliably, then I'll take a shot at fixing it.

**Comment by kdsteckel** [comment] 2020-06-05 18:25
Example of a consistent example of not falling through a dug hole 
![ConsistentNotFallingExample](https://user-images.githubusercontent.com/50111166/83910110-9a2a8200-a72f-11ea-8171-3103c3a9be07.png)
![Screen Shot 2020-06-05 at 1 19 41 PM](https://user-images.githubusercontent.com/50111166/83910150-a7e00780-a72f-11ea-9666-407c7637051a.png)
![ConsistentNotFallingExample](https://user-images.githubusercontent.com/50111166/83910177-b29a9c80-a72f-11ea-9141-cdc5a7c91dca.png)
To produce this error that does not allow you to fall through this hole you: 
Climb the ladder to the right and trap that enemy that is on that level
Dig the all three diggable ground tiles on the first layer
Then dig the two diggable tiles that will let you through to where the gold is 
Then dig the tile on the right and you will not be allowed to fall through 
@schrum2

**Comment by schrum2** [comment] 2020-06-05 18:33
What code do I run? @kdsteckel

**Comment by kdsteckel** [comment] 2020-06-05 18:34
Game.java

**Comment by schrum2** [comment] 2020-06-05 18:54
Solved (see previous commit message), and closing

**Closed by schrum2** 2020-06-05 18:54 UTC
Labels: Lode Runner
